theme: jekyll-theme-cayman
title: "Career Optimization Utilizing Census Data"
description: "CS7641 Project: Group 11 (Aakash Bajpai, Joshua Fernandez, Sharjeel Khan, Pooja Moolchandani, Andrew Namgoong)"
